<?php
/**
 * This file was generated by a PHP script on 09/15/2008 at 20:32:06
 * 
 * File : /home/gcroes/workspace/Copix_3/project/modules/stable/standard/auth/classes/useconfigurationfile.class.php
 * Line : 44
 * Function : useConfigurationFile->write
 */

$_credential_handlers = array (
  'admin|installcredentialhandler' => 
  array (
    'name' => 'admin|installcredentialhandler',
    'stopOnSuccess' => true,
    'stopOnFailure' => false,
  ),
  'auth|dbcredentialhandler' => 
  array (
    'name' => 'auth|dbcredentialhandler',
    'stopOnSuccess' => true,
    'stopOnFailure' => false,
  ),
  'auth|dbmodulecredentialhandler' => 
  array (
    'name' => 'auth|dbmodulecredentialhandler',
    'stopOnSuccess' => true,
    'stopOnFailure' => false,
    'handle' => 
    array (
      0 => 'module',
    ),
  ),
);

?>