<?php
/**
 * This file was generated by a PHP script on 09/15/2008 at 20:31:39
 * 
 * File : /home/gcroes/workspace/Copix_3/project/modules/stable/standard/auth/classes/useconfigurationfile.class.php
 * Line : 44
 * Function : useConfigurationFile->write
 */

$_group_handlers = array (
  'auth|dbgrouphandler' => 
  array (
    'name' => 'auth|dbgrouphandler',
    'required' => NULL,
  ),
);

?>