<?php
/**
 * This file was generated by a PHP script on 09/15/2008 at 20:31:34
 * 
 * File : /home/gcroes/workspace/Copix_3/project/modules/stable/standard/auth/classes/useconfigurationfile.class.php
 * Line : 44
 * Function : useConfigurationFile->write
 */

$_user_handlers = array (
  'auth|dbuserhandler' => 
  array (
    'name' => 'auth|dbuserhandler',
    'required' => false,
    'rank' => NULL,
  ),
);

?>